# Generated by Django 3.2.4 on 2021-06-26 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name of Registration')),
                ('activity_date', models.DateField(verbose_name='Date of Activity')),
                ('date_registered', models.DateTimeField(auto_now_add=True, verbose_name='Date Registered')),
                ('is_closed', models.BooleanField(default=True, verbose_name='Registration Closed?')),
                ('type', models.CharField(choices=[('SUNDAY_SERVICE', 'Sunday service'), ('EVENT', 'Event')], default='SUNDAY_SERVICE', max_length=20, verbose_name='Type of Registration')),
            ],
        ),
        migrations.CreateModel(
            name='CancelledRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_date', models.DateTimeField(auto_now_add=True, verbose_name='Cancellation Date')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.registration', verbose_name='Registration to be cancelled')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=80, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=80, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=80, verbose_name='Surname')),
                ('patronic_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Patronic Name')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(verbose_name='Updated At')),
                ('is_student_or_young_adult', models.BooleanField(default=False, verbose_name='Student or Young Adult?')),
                ('cancelled_registrations', models.ManyToManyField(blank=True, to='api.CancelledRegistration', verbose_name='Cancelled Registrations')),
                ('registrations', models.ManyToManyField(blank=True, to='api.Registration', verbose_name='Registrations')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
