# Generated by Django 3.2.4 on 2021-06-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated At'),
        ),
    ]
