# Generated by Django 3.2.4 on 2021-06-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_person_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='homegroup',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Home Group'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_member',
            field=models.BooleanField(blank=True, default=True, verbose_name='Member of Hope Church?'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
